services:
  rabbitmq-test:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-test
    ports:
      - "5673:5672"
      - "15673:15672"
    environment: 
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
      RABBITMQ_DEFAULT_VHOST: /test

  postgres-test:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: magic-pages-test
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data
